#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Validate the repository's generated pip hash-lock contract."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "requirements"
LOCK_NAMES = ("lock-tools", "runtime", "build", "ci", "security", "sbom", "fuzz")
PIN = re.compile(r"^[A-Za-z0-9_.-]+==[^\s\\]+(?:\s*\\)?$")
HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}(?:\s*\\)?$")


def validate_lock(path: Path) -> list[str]:
    errors: list[str] = []
    lines = path.read_text(encoding="utf-8").splitlines()
    if "autogenerated by pip-compile" not in "\n".join(lines[:8]):
        errors.append(f"{path.name}: missing pip-compile provenance header")
    if "--no-index" in "\n".join(lines[:10]):
        errors.append(f"{path.name}: host-specific --no-index leaked into header")

    requirement_indexes = [
        index
        for index, line in enumerate(lines)
        if line and not line.startswith((" ", "#", "-"))
    ]
    if not requirement_indexes:
        errors.append(f"{path.name}: lock is empty")
    for position, index in enumerate(requirement_indexes):
        line = lines[index]
        if not PIN.fullmatch(line):
            errors.append(f"{path.name}:{index + 1}: dependency is not exactly pinned")
            continue
        end = requirement_indexes[position + 1] if position + 1 < len(requirement_indexes) else len(lines)
        if not any(HASH.search(candidate.strip()) for candidate in lines[index + 1 : end]):
            errors.append(f"{path.name}:{index + 1}: exact pin has no SHA-256 hash")
    return errors


def validate_repository() -> list[str]:
    errors: list[str] = []
    for name in LOCK_NAMES:
        source = REQUIREMENTS / f"{name}.in"
        lock = REQUIREMENTS / f"{name}.lock.txt"
        if not source.is_file():
            errors.append(f"missing {source.relative_to(ROOT)}")
        if not lock.is_file():
            errors.append(f"missing {lock.relative_to(ROOT)}")
            continue
        errors.extend(validate_lock(lock))
    return errors


def main() -> int:
    errors = validate_repository()
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print("dependency locks: passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
